import express from'express';import helmet from'helmet';import cors from'cors';import{rateLimit}from'express-rate-limit';import{z}from'zod';import{q}from'./db.mjs';const app=express();app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:(process.env.CORS_ORIGIN||'http://localhost:3001').split(',')}));app.use(express.json({limit:'2mb'}));app.use(rateLimit({windowMs:60_000,limit:120}));const safe=f=>(a,b,c)=>Promise.resolve(f(a,b,c)).catch(c);const role=(...allowed)=>(req,res,next)=>{const r=req.headers['x-demo-role']||'SUPER_ADMIN';if(allowed.includes(r))return next();return res.status(401).json({error:'Configure OIDC/MFA para producción'})};
app.get('/health',safe(async(_,r)=>{if(process.env.DATABASE_URL)await q('SELECT 1');r.json({status:'ok',service:'api-empleados'})}));
app.get('/v1/dashboard',role('SUPER_ADMIN','MANAGER','FINANCE'),safe(async(_,res)=>{const [p,e]=await Promise.all([q("SELECT count(*)::int total,count(*) FILTER(WHERE status='AVAILABLE')::int available FROM properties"),q("SELECT COALESCE(sum(amount),0)::float expenses FROM expenses WHERE occurred_on>=date_trunc('month',now())")]);res.json({...p.rows[0],...e.rows[0]})}));
app.get('/v1/properties',role('SUPER_ADMIN','MANAGER','RECEPTION','HOUSEKEEPING'),safe(async(_,res)=>res.json({items:(await q('SELECT * FROM properties ORDER BY updated_at DESC')).rows})));
app.post('/v1/properties',role('SUPER_ADMIN','MANAGER'),safe(async(req,res)=>{const d=z.object({name:z.string().min(3),type:z.enum(['HOTEL','ROOM','HOUSE','APARTMENT','SUITE']),city:z.string(),address:z.string().optional(),maxGuests:z.number().int().positive(),basePrice:z.number().nonnegative(),details:z.record(z.string(),z.any()).optional()}).parse(req.body);const {rows}=await q('INSERT INTO properties(name,type,city,address,max_guests,base_price,details) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[d.name,d.type,d.city,d.address,d.maxGuests,d.basePrice,d.details||{}]);await q("INSERT INTO audit_log(action,resource,resource_id) VALUES('CREATE','PROPERTY',$1)",[rows[0].id]);res.status(201).json(rows[0])}));
app.post('/v1/properties/:id/publish',role('SUPER_ADMIN','MANAGER'),safe(async(req,res)=>{const {rows}=await q("UPDATE properties SET published=true,version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[req.params.id]);if(!rows[0])return res.status(404).end();const p=rows[0],url=process.env.CLIENT_API_URL;if(url){const r=await fetch(url+'/internal/catalog',{method:'POST',headers:{'content-type':'application/json','x-sync-secret':process.env.ADMIN_SYNC_SECRET||''},body:JSON.stringify({id:p.id,name:p.name,type:p.type,city:p.city,maxGuests:p.max_guests,basePrice:Number(p.base_price),details:p.details,media:p.media,version:Number(p.version)})});if(!r.ok)return res.status(502).json({error:'No fue posible sincronizar',property:p})}res.json({property:p,synced:Boolean(url)})}));
app.get('/v1/expenses',role('SUPER_ADMIN','FINANCE'),safe(async(_,res)=>res.json({items:(await q('SELECT * FROM expenses ORDER BY occurred_on DESC')).rows})));
app.post('/v1/expenses',role('SUPER_ADMIN','FINANCE'),safe(async(req,res)=>{const d=z.object({category:z.string(),kind:z.enum(['FIXED','VARIABLE','ASSET']),description:z.string(),amount:z.number().positive(),occurredOn:z.string()}).parse(req.body);res.status(201).json((await q('INSERT INTO expenses(category,kind,description,amount,occurred_on) VALUES($1,$2,$3,$4,$5) RETURNING *',[d.category,d.kind,d.description,d.amount,d.occurredOn])).rows[0])}));
app.use((e,req,res,next)=>{console.error(e.message);res.status(e.name==='ZodError'?400:500).json({error:e.name==='ZodError'?'Datos inválidos':'Error interno'})});app.listen(process.env.PORT||4001,()=>console.log('API empleados lista'));
