import express from'express';import helmet from'helmet';import cors from'cors';import{rateLimit}from'express-rate-limit';import{z}from'zod';import{hash,verify}from'@node-rs/argon2';import{SignJWT,jwtVerify}from'jose';import{q}from'./db.mjs';
const app=express(),prod=process.env.NODE_ENV==='production',secret=new TextEncoder().encode(process.env.JWT_SECRET||'development-secret-change-this-now');if(prod&&secret.length<32)throw Error('JWT_SECRET inseguro');app.disable('x-powered-by');app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:(process.env.CORS_ORIGIN||'http://localhost:3000').split(','),credentials:true}));app.use(express.json({limit:'1mb'}));app.use(rateLimit({windowMs:60_000,limit:100,standardHeaders:'draft-8'}));
const safe=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);const token=u=>new SignJWT({sub:u.id,email:u.email}).setProtectedHeader({alg:'HS256'}).setIssuedAt().setExpirationTime('15m').sign(secret);async function auth(req,res,next){try{req.user=(await jwtVerify((req.headers.authorization||'').replace('Bearer ',''),secret)).payload;next()}catch{return res.status(401).json({error:'No autorizado'})}}
app.get('/health',safe(async(_,r)=>{if(process.env.DATABASE_URL)await q('SELECT 1');r.json({status:'ok',service:'api-clientes'})}));
app.get('/v1/properties',safe(async(req,res)=>{if(!process.env.DATABASE_URL)return res.json({items:[]});const {rows}=await q('SELECT id,name,type,city,max_guests AS "maxGuests",base_price::float AS "basePrice",details,media FROM properties WHERE available=true ORDER BY updated_at DESC LIMIT 100');res.json({items:rows})}));
app.post('/v1/auth/register',safe(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string().min(12).max(128),name:z.string().min(2).max(80)}).parse(req.body);const {rows}=await q('INSERT INTO users(email,password_hash,name) VALUES(lower($1),$2,$3) RETURNING id,email,name',[d.email,await hash(d.password),d.name]);res.status(201).json({user:rows[0],accessToken:await token(rows[0])})}));
app.post('/v1/auth/login',safe(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const {rows}=await q('SELECT * FROM users WHERE email=lower($1)',[d.email]);if(!rows[0]||!await verify(rows[0].password_hash,d.password))return res.status(401).json({error:'Credenciales inválidas'});res.json({accessToken:await token(rows[0])})}));
app.post('/v1/reservations/hold',auth,safe(async(req,res)=>{const d=z.object({propertyId:z.string().uuid(),from:z.coerce.date(),to:z.coerce.date(),guests:z.number().int().positive(),idempotencyKey:z.string().min(12)}).parse(req.body);const c=await q('SELECT id FROM reservations WHERE property_id=$1 AND status IN(\'HOLD\',\'PAID\') AND (status=\'PAID\' OR hold_until>now()) AND starts_on<$3 AND ends_on>$2 LIMIT 1',[d.propertyId,d.from,d.to]);if(c.rowCount)return res.status(409).json({error:'Fechas no disponibles'});const {rows}=await q("INSERT INTO reservations(user_id,property_id,starts_on,ends_on,guests,hold_until,idempotency_key) VALUES($1,$2,$3,$4,$5,now()+interval '15 minutes',$6) ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *",[req.user.sub,d.propertyId,d.from,d.to,d.guests,d.idempotencyKey]);res.status(201).json(rows[0])}));
app.post('/internal/catalog',safe(async(req,res)=>{if(req.headers['x-sync-secret']!==process.env.ADMIN_SYNC_SECRET)return res.status(401).end();const d=z.object({id:z.string().uuid(),name:z.string(),type:z.string(),city:z.string(),maxGuests:z.number().int(),basePrice:z.number(),details:z.record(z.string(),z.any()).optional(),media:z.array(z.any()).optional(),version:z.number().int()}).parse(req.body);await q(`INSERT INTO properties(id,name,type,city,max_guests,base_price,details,media,source_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET name=$2,type=$3,city=$4,max_guests=$5,base_price=$6,details=$7,media=$8,source_version=$9,updated_at=now() WHERE properties.source_version<$9`,[d.id,d.name,d.type,d.city,d.maxGuests,d.basePrice,d.details||{},JSON.stringify(d.media||[]),d.version]);res.status(202).json({accepted:true})}));
app.use((e,req,res,next)=>{console.error(e.message);res.status(e.name==='ZodError'?400:500).json({error:e.name==='ZodError'?'Datos inválidos':'Error interno',requestId:req.headers['x-request-id']})});app.listen(process.env.PORT||4000,()=>console.log('API clientes lista'));
